# Generated by Django 4.2.3 on 2023-07-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_title", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=20)),
                ("energy", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Middle"), ("L", "Large")],
                        max_length=10,
                    ),
                ),
                (
                    "area",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="mac.area"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_title", models.CharField(max_length=20)),
                (
                    "for_who",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Middle"), ("L", "Large")],
                        max_length=20,
                    ),
                ),
                ("product", models.ManyToManyField(to="mac.product")),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mac.restaurant",
                    ),
                ),
            ],
        ),
    ]
