# Generated by Django 4.2.3 on 2023-07-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="area_title",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
