# Generated by Django 4.2.3 on 2023-07-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mac", "0002_alter_area_area_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="for_who",
            field=models.CharField(
                choices=[
                    ("F1", "For 1 person"),
                    ("F2", "For 2 person"),
                    ("FK", "For kids"),
                ],
                max_length=20,
            ),
        ),
    ]
